version: '3.1'

services:
  db:
    build:
      context: .
      target: dellstore
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data

  db_isolated:
    build:
      context: .
      target: dellstore_isolated
    restart: always
    ports:
      - 3456:5432
    environment:
      POSTGRES_DB: ${ISOLATED_ENV_DB_NAME}
      POSTGRES_USER: ${ISOLATED_ENV_DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_isolated_password
    secrets:
      - db_isolated_password
    volumes:
      - db_isolated_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
      # - db_isolated
    build:
      context: .
      target: backend
    ports:
      - 5000:5000
    restart: always
    environment:
      DATABASE_URI: ${DATABASE_URI}
      APPSETTINGS: ${APPSETTINGS}
      FLASK_ENV: ${ENV}
    volumes:
      - ./:/app

secrets:
  db_password:
    file: ./db_password
  db_isolated_password:
    file: ./db_isolated_password

volumes:
  db_data:
  db_isolated_data: